name: Publish Package

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install Dependencies
        run: |
          python3 -m pip3 install --upgrade pip3
          pip3 install setuptools wheel twine

      - name: Build Package
        run: python3 setup.py sdist bdist_wheel

      - name: Publish Package to PyPI
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          python3 -m twine upload dist/*
